/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sample_hello_HelloTest */

#ifndef _Included_com_sample_hello_HelloTest
#define _Included_com_sample_hello_HelloTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sample_hello_HelloTest
 * Method:    ndkHelloTest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sample_hello_HelloTest_ndkHelloTest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
